version: '3.4'

networks:
  rede_olap:
  rede_oltp:
  rede_message_broker:
  rede_externa:

services:
  message_broker:
    container_name: message_broker
    restart: always
    image: rabbitmq:3-management
    networks:
      - rede_message_broker

  banco_analitico:
    container_name: banco_analitico
    restart: always
    image: mongo:3.6
    networks:
      - rede_olap

  banco_transacional:
    container_name: banco_transacional
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: banco_transacional
    networks:
      - rede_oltp

  fluxodecaixa.lancamentos.api:
    image: ${DOCKER_REGISTRY-}fluxodecaixalancamentosapi
    build:
      context: .
      dockerfile: src/FluxoDeCaixa.Lancamentos.Api/Dockerfile
    depends_on:
      - message_broker
    networks:
      - rede_externa
      - rede_message_broker

  fluxodecaixa.lancamentos.workers:
    image: ${DOCKER_REGISTRY-}fluxodecaixalancamentosworkers
    build:
      context: .
      dockerfile: src/FluxoDeCaixa.Lancamentos.Workers/Dockerfile
    depends_on:
      - message_broker
      - banco_transacional
    networks:
      - rede_message_broker
      - rede_oltp

  fluxodecaixa.fluxos.workers:
    image: ${DOCKER_REGISTRY-}fluxodecaixafluxosworkers
    build:
      context: .
      dockerfile: src/FluxoDeCaixa.Fluxos.Workers/Dockerfile
    depends_on:
      - message_broker
      - banco_analitico
    networks:
      - rede_message_broker
      - rede_olap

  fluxodecaixa.fluxos.api:
    image: ${DOCKER_REGISTRY-}fluxodecaixafluxosapi
    build:
      context: .
      dockerfile: src/FluxoDeCaixa.Fluxos.Api/Dockerfile
    depends_on:
      - banco_analitico
    networks:
      - rede_externa
      - rede_olap

  fluxodecaixa.politicas.workers:
    image: ${DOCKER_REGISTRY-}fluxodecaixapoliticasworkers
    build:
      context: .
      dockerfile: src/FluxoDeCaixa.Politicas.Workers/Dockerfile
    depends_on:
      - message_broker
      - banco_transacional
    networks:
      - rede_message_broker
      - rede_oltp
