version: '3.4'

services:
  message_broker:
    #volumes:
    #  - ./data/message_broker:/var/lib/rabbitmq/mnesia/
    #ports:
    #  - "5672:5672"
    ports:
      - "15672:15672"

  banco_analitico:
    volumes:
      - ./data/banco_analitico:/data/db
    #ports:
    #  - "27017:27017"

  banco_transacional:
    #volumes:
    #  - ./data/banco_transacional:/var/opt/mssql/data
    #  - ./data/banco_transacional/log:/var/opt/mssql/log
    #  - ./data/banco_transacional/secrets:/var/opt/mssql/secrets
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BigPassw0rd"
      MSSQL_AGENT_ENABLED: "true"
    #ports:
    #  - "1433:1433"

  fluxodecaixa.lancamentos.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  fluxodecaixa.lancamentos.workers:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  fluxodecaixa.fluxos.workers:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  fluxodecaixa.politicas.workers:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  fluxodecaixa.fluxos.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
